
// New priority system based on user requirements
export function getFamilyPriority(familyName) {
  const priorities = {
  "MovementVelocity": 1,
  "ChanceToSuppressSpells": 2,
  "ChanceToSuppressSpells2": 2,
  "ChaosResistance": 3,
  "FireResistance": 4,
  "ColdResistance": 5,
  "LightningResistance": 6,
  "MaximumFireResist": 7,
  "MaximumColdResist": 8,
  "MaximumLightningResistance": 9,
  "MaximumChaosResistance": 10,
  "LifeRegenerationRate": 11,
  "IncreasedLife": 12,
  "IncreasedLife2": 12,
  "IncreasedLife22": 12,
  "IncreasedLife3": 12,
  "IncreasedLife4": 12,
  "MinionLifeX": 12,
  "MinionLifeX2": 12,
  "ArmourEnergyShieldPercent": 13,
  "ArmourEnergyShieldPercent2": 13,
  "ArmourEnergyShieldPercent22": 13,
  "ArmourEvasionPercent": 13,
  "ArmourEvasionPercent2": 13,
  "ArmourEvasionPercent22": 13,
  "ArmourPercent": 13,
  "ArmourPercent2": 13,
  "ArmourPercentIncreasedArmour": 13,
  "BaseArmour": 13,
  "BaseArmour2": 13,
  "BaseArmour3": 13,
  "BaseArmourEnergyShield2": 13,
  "BaseArmourEnergyShield22": 13,
  "BaseArmourEnergyShield222": 13,
  "BaseArmourEnergyShield3": 13,
  "BaseArmourEvasion2": 13,
  "BaseArmourEvasion22": 13,
  "BaseArmourEvasion222": 13,
  "BaseEnergyShield2": 13,
  "BaseEnergyShield22": 13,
  "BaseEnergyShield222": 13,
  "BaseEnergyShield32": 13,
  "BaseEvasion": 13,
  "BaseEvasion2": 13,
  "BaseEvasion3": 13,
  "BaseEvasionEnergyShield2": 13,
  "BaseEvasionEnergyShield22": 13,
  "BaseEvasionEnergyShield222": 13,
  "EnergyShieldDelay": 13,
  "EnergyShieldPercent": 13,
  "EnergyShieldPercent2": 13,
  "EnergyShieldPercent22": 13,
  "EnergyShieldPercentIncreasedEnergy2": 13,
  "EnergyShieldRegeneration": 13,
  "EvasionEnergyShieldPercent": 13,
  "EvasionEnergyShieldPercent2": 13,
  "EvasionEnergyShieldPercent22": 13,
  "EvasionPercent": 13,
  "EvasionPercent2": 13,
  "EvasionPercentIncreasedEvasion": 13,
  "EvasionRatingPercent": 13,
  "IncreasedEnergyShield": 13,
  "IncreasedEnergyShield2": 13,
  "IncreasedEvasionRating": 13,
  "IncreasedPhysicalDamageReductionRating": 13,
  "IncreasedPhysicalDamageReductionRatingPercent": 13,
  "LocalIncreasedPhysicalDamagePercentAndAccuracyRating": 14,
  "LocalPhysicalDamagePercent": 14,
  "PhysicalDamage": 15,
  "PhysicalDamage2": 15,
  "PhysicalDamage22": 15,
  "PhysicalDamage222": 15,
  "PhysicalDamageAddsTo2": 15,
  "PhysicalDamageAddsTo222": 15,
  "AllGemChaos": 16,
  "AllGemChaos3": 16,
  "AllGemCold": 16,
  "AllGemCold3": 16,
  "AllGemFire": 16,
  "AllGemFire3": 16,
  "AllGemLightning": 16,
  "AllGemLightning3": 16,
  "AllGemMinion": 16,
  "AllGemPhysical": 16,
  "AllGemPhysical3": 16,
  "AllMinionGemLevel": 16,
  "GlobalDamageTypeGemLevel": 16,
  "GlobalDamageTypeGemLevel1To": 16,
  "GlobalDamageTypeGemLevel1To2": 16,
  "GlobalDamageTypeGemLevel1To3": 16,
  "GlobalDamageTypeGemLevel1To4": 16,
  "GlobalSkillGemLevel": 16,
  "IncreaseSocketedGemLevel": 16,
  "IncreaseSocketedGemLevel2": 16,
  "AvoidElementalStatusAilments": 17,
  "IncreasedAttackSpeed": 18,
  "IncreasedAttackSpeed2": 18,
  "IncreasedAttackSpeed22": 18,
  "SpellBlockPercentage": 19,
  "SpellDamage": 19,
  "SpellDamageAndMana": 19,
  "SpellDamageMana": 19,
  "SpellPercentage2": 19,
  "IncreasedCastSpeed": 20,
  "IncreasedCastSpeed2": 20,
  "IncreasedCastSpeed22": 20,
  "IncreasedCastSpeed3": 20,
  "IncreasedShieldBlockPercentage": 21,
  "IncreasedMana": 22,
  "IncreasedMana2": 22,
  "IncreasedMana22": 22,
  "IncreasedMana222": 22,
  "IncreasedMana3": 22,
  "IncreasedWeaponElementalDamagePercent": 23,
  "IncreasedWeaponElementalDamagePercent2": 23,
  "IncreasedWeaponElementalDamagePercent222": 23,
  "CriticalStrikeMultiplier": 24,
  "CriticalStrikeMultiplierToGlobal": 24,
  "CriticalStrikeChanceIncrease": 25,
  "CriticalStrikeChanceIncrease2": 25,
  "CriticalStrikeChanceIncreaseIncreasedGlobal2": 25,
  "SpellCriticalStrikeChanceIncrease": 25,
  "ChaosDOTMultiplier": 26,
  "ChaosDOTMultiplier2": 26,
  "ChaosDOTMultiplier22": 26,
  "ColdDOTMultiplier": 26,
  "ColdDOTMultiplier2": 26,
  "FireDOTMultiplier": 26,
  "FireDOTMultiplier2": 26,
  "GlobalDamageOverTimeMultiplier": 26,
  "GlobalDamageOverTimeMultiplier2": 26,
  "GlobalDamageOverTimeMultiplier22": 26,
  "PhysicalDOTMultiplier": 26,
  "PhysicalDOTMultiplier2": 26,
  "AllAttributes": 27,
  "AllAttributes2": 27,
  "Dexterity": 27,
  "Dexterity2": 27,
  "Intelligence": 27,
  "Intelligence2": 27,
  "Strength": 27,
  "Strength2": 27,
  "AllResistances": 28,
  "AllResistances2": 28,
  "MinionElementalResistancesX": 28,
  "MinionElementalResistancesX2": 28,
  "MinionAttackSpeedAndCastSpeed": 28,
  "MinionAttackSpeedAndCastSpeedX": 28,
  "MinionDamageMana": 28,
  "MinionCriticalStrikeMultiplier": 28,
  "MinionCriticalStrikeChance": 28,
  "MinionCriticalStrikeChanceX2": 28,
  "MinionDamagePercentage": 28,
  "MinionDamageX": 28,
  "MinionMovementSpeedX": 28,
  "MinionDamageX2": 28,
  "MinionPhysicalDamageReductionX2": 28,
  "MinionAccuracyRating": 28,
  "MinionLifeX": 28,
  "MinionLifeX2": 28,
  "FireDamage": 29,
  "FireDamage2": 29,
  "FireDamage22": 29,
  "FireDamageAddsTo22": 29,
  "FireDamageAddsTo222": 29,
  "SpellAddedFireDamage": 29,
  "SpellAddedFireDamage2": 29,
  "ColdDamage": 30,
  "ColdDamage2": 30,
  "ColdDamage22": 30,
  "ColdDamageAddsTo22": 30,
  "ColdDamageAddsTo222": 30,
  "SpellAddedColdDamage": 30,
  "SpellAddedColdDamage2": 30,
  "LightningDamage": 31,
  "LightningDamage2": 31,
  "LightningDamage22": 31,
  "LightningDamageAddsTo2": 31,
  "LightningDamageAddsTo22": 31,
  "LightningDamageAddsTo222": 31,
  "SpellAddedLightningDamage": 31,
  "SpellAddedLightningDamage2": 31,
  "AdditionalArrows": 33,
  "AdditionalArrows2": 33,
  "AdditionalArrowsBowAttacks2": 33,
  "BeltFlaskCharges": 34,
  "BeltFlaskDuration": 34,
  "BeltFlaskRecoveryRate": 34,
  "BeltFlaskRecoveryRateIncreasedFlask": 34,
  "FlaskEffect": 34,
  "ChanceToFreeze": 35,
  "ChanceToFreeze2": 35,
  "ChanceToIgnite": 35,
  "ChanceToIgnite2": 35,
  "ChanceToShock": 35,
  "ChanceToShock2": 35,
  "ChaosDamage": 36,
  "LocalChaosDamage": 36,
  "LocalChaosDamage2": 36,
  "ColdDamagePercentage": 37,
  "ColdDamagePercentage2": 37,
  "ColdDamagePercentage3": 37,
  "ColdDamagePercentagePrefix": 37,
  "ColdDamagePercentagePrefix2": 37,
  "FireDamagePercentage": 37,
  "FireDamagePercentage2": 37,
  "FireDamagePercentage3": 37,
  "FireDamagePercentagePrefix": 37,
  "FireDamagePercentagePrefix2": 37,
  "LightningDamagePercentage": 37,
  "LightningDamagePercentage2": 37,
  "LightningDamagePercentage3": 37,
  "LightningDamagePercentagePrefix": 37,
  "LightningDamagePercentagePrefix2": 37,
  "SpellPercentage22": 37,
  "SpellPercentageIncreasedFire22": 37,
  "SpellPercentageIncreasedLightning22": 37,
  "DamageTakenGainedAsLife": 38,
  "IncreaseSocketedGemLevel1To2": 39,
  "SocketedBowGemLevel": 39,
  "SocketedChaosGemLevel": 39,
  "SocketedColdGemLevel": 39,
  "SocketedFireGemLevel": 39,
  "SocketedLightningGemLevel": 39,
  "SocketedMeleeGemLevel": 39,
  "IncreaseSocketedGemLevelX": 39,
  "IncreasedAccuracy": 40,
  "IncreasedAccuracy2": 40,
  "IncreasedAccuracy22": 40,
  "IncreasedAccuracy222": 40,
  "LightRadiusAndAccuracy": 40,
  "LightRadiusAndAccuracyIncreasedGlobal": 40,
  "LightRadiusAndAccuracyIncreasedGlobal2": 40,
  "ItemFoundRarityIncrease": 41,
  "ItemFoundRarityIncrease2": 41,
  "ItemFoundRarityIncreasePrefix": 41,
  "ItemFoundRarityIncreasePrefix2": 41,
  "ItemFoundRarityIncreasePrefix3": 41,
  "LifeGainPerTarget": 42,
  "LifeGainPerTarget2": 42,
  "LifeGainPerTargetGrantsLife2": 42,
  "LifeGainedFromEnemyDeath": 42,
  "LifeRegenerationBodyArmour": 42,
  "LifeRegenerationBoots": 42,
  "LifeRegenerationHelmets": 42,
  "LifeRegenerationShield": 42,
  "LifeLeech": 43,
  "LifeLeech2": 43,
  "LifeLeechAttackWeapons2": 43,
  "LifeLeechJewellery222": 43,
  "ManaLeech": 43,
  "ManaLeech2": 43,
  "ManaLeech222": 43,
  "LocalAttributeRequirements": 44,
  "LocalAttributeRequirements32Reduced": 44,
  "ManaGainedFromEnemyDeath": 45,
  "ProjectileSpeed": 46,
  "ReducedExtraDamageFromCrits": 47,
  "StunDurationIncreasePercent": 48,
  "AttackerTakesDamageNoRange": 49,
  "AttackerTakesDamageNoRange2": 49,
  "StunRecovery": 50,
  "StunThresholdReduction": 51,
  "BaseArmourAndLife": 52,
  "BaseArmourAndLife2": 52,
  "BaseArmourAndLife3": 52,
  "BaseEnergyShieldAndLife": 52,
  "BaseEnergyShieldAndLife22": 52,
  "BaseEnergyShieldAndMana": 52,
  "BaseEnergyShieldAndMana2": 52,
  "BaseEnergyShieldAndMana22": 52,
  "BaseEnergyShieldAndMana222": 52,
  "BaseEnergyShieldAndMana3": 52,
  "BaseEvasionAndLife": 52,
  "BaseEvasionAndLife2": 52,
  "BaseEvasionAndLife3": 52,
  "DamageWithWeaponTypeSkill": 52,
  "ManaRegeneration": 52,
  "ManaRegeneration2": 52,
  "MaximumResistances": 52,
  "ReducedPhysicalDamageTaken": 52,
  "GrantedSkillX2": 52
};
  return priorities[familyName] || 52;
}

// Priority order for reference
export const PRIORITY_ORDER = [
  "Movement Speed",
  "Chance to Suppress Spell Damage",
  "Chaos Resistance",
  "Fire Resistance",
  "Cold Resistance", 
  "Lightning Resistance",
  "Maximum Fire Resistance",
  "Maximum Cold Resistance",
  "Maximum Lightning Resistance",
  "Maximum Chaos Resistance",
  "Life Regeneration Rate (percent)",
  "Increased Life (solo)",
  "Increased Armour/Evasion/ES (not with life/mana)",
  "Physical Damage % (attack weapons)",
  "Physical Damage flat (attack weapons)",
  "+# to Level of all Gems (not socketed)",
  "Chance to Avoid Elemental Ailments",
  "Attack Speed",
  "Spell Damage",
  "Cast Speed",
  "Chance to Block",
  "Mana (by itself)",
  "Elemental Damage with Attacks",
  "Critical Strike Multiplier",
  "Critical Strike Chance",
  "Damage over Time Multiplier",
  "Attributes (Int/Dex/Str)",
  "All Resistances",
  "Adds Fire Damage",
  "Adds Cold Damage",
  "Adds Lightning Damage",
  "Minion Related",
  "Additional Arrows",
  "Flask Effects",
  "Chance to Ailment",
  "Chaos Damage",
  "Elemental Damage %",
  "Damage Recoup",
  "Socketed Gem Levels",
  "Accuracy Rating",
  "Item Rarity",
  "Life Gain on Hit/Kill",
  "Leech",
  "Attribute Requirements",
  "Mana Gain on Hit/Kill",
  "Projectile Speed",
  "Reduced Damage Taken",
  "Stun Duration",
  "Reflects Physical Damage",
  "Stun and Block Recovery (solo)",
  "Stun Threshold",
  "Default Priority"
];
